### ISSUE TITLE
The language change by itself

### ISSUE THREAD

**Issue by somebodytoo** [iamdowner/nhentai-telegram-bot#16] opened 2022-03-17 08:21 UTC
The language randomly change by itself, unable to change back to english, sometime change to russian, sometime change to spainish

**Comment by sleroq** [comment] 2022-04-12 21:03
Hello, sorry for the late reply.

I can't reproduce this issue, Is it still relevant? 
Is this problem occurs in a public instance or in your particular case?

**Comment by sleroq** [comment] 2022-12-21 21:40
Closing - no feedback

**Closed as completed by sleroq** 2022-12-21 21:40 UTC
